# Generated by Django 5.1.4 on 2025-05-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_library_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_management',
            name='class_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library_management',
            name='image',
            field=models.ImageField(default=1, upload_to='Media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library_management',
            name='section',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library_management',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='school.students'),
        ),
    ]
