# Generated by Django 5.1.4 on 2025-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_library_management_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('Edition', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='library_management',
        ),
    ]
