# Generated by Django 5.1.4 on 2025-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_library_records_delete_library_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_records',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
