# Generated by Django 5.1.4 on 2025-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_library_records_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_records',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
