# Generated by Django 5.1.4 on 2025-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_library_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
